/**:
  ros__parameters:
    fiducial_sim_enabled: true
    fiducial_gt_max_dt_sec: 1.0
    body_T_camera_x: 0.10
    body_T_camera_y: 0.03
    body_T_camera_z: 0.03
    body_T_camera_roll_deg: 0.0
    body_T_camera_pitch_deg: -90.0
    body_T_camera_yaw_deg: 90.0
    use_camera_optical_frame_convention: true
    fiducial_1_x: 0.0
    fiducial_1_y: 9.0
    fiducial_1_z: 1.0
    fiducial_1_radius: 2.0
    fiducial_2_x: 0.0
    fiducial_2_y: -9.0
    fiducial_2_z: 1.0
    fiducial_2_radius: 2.0
