/**:
  ros__parameters:
    # !Cuidado con poner trayy xacro juntos: mismo nombre!
    fisico.brazos.longitud: 0.25               # en m (respecto al centro del cuerpo) 
    fisico.brazos.grados: 45.0                # grados respecto al frente 

    fisico.constante.gravedad: -9.81          # en m/s²

    
    control.fuerza.kp: 2.0
    control.fuerza.kv: 7.0

    control.torque.kr: 0.1
    control.torque.kw: 0.1


    actuadores.conversor.fuerza2torque: 0.02


    control.tray.usar_veltrap: 'true'      # necesita ser string


    crear.tray.v_max_lin: 0.8
    crear.tray.v_max_ang: 0.5
    crear.tray.t_a: 5.0
