window.FLOW_GRAPH = {
  categories: {
    ingest: { label: 'Ingesta raw', color: '#396ca8', active: '#0b67c2' },
    pose: { label: 'Anchors y poses', color: '#a76413', active: '#df7a00' },
    secondary: { label: 'Trabajo secundario', color: '#87506a', active: '#bd2f68' },
    derived: { label: 'Estado derivado', color: '#37795a', active: '#00844b' },
    publication: { label: 'Publicación', color: '#167984', active: '#009aa8' }
  },
  nodes: [
    ['wrappers', 'Wrappers ORB-SLAM3', 90, 300, 'Publican deltas frecuentes y snapshots completos por dron.', 'ingest'],
    ['server', 'GlobalMapServer', 300, 300, 'Coordina callbacks, commits breves, tareas y publicación asíncrona.', 'ingest'],
    ['raw_db', 'RawMapDatabase', 520, 120, 'Conserva KFs, MapPoints, revisiones y journal ORB-SLAM3 sin correcciones.', 'ingest'],
    ['fiducial', 'FiducialAnchorManager', 520, 300, 'Asocia observaciones, crea el primer anchor y detecta revisitas.', 'pose'],
    ['queue', 'SecondaryTaskQueue', 520, 520, 'Mantiene una sola tarea activa, fiduciales con prioridad y loops FIFO.', 'secondary'],
    ['pose_db', 'GlobalPoseStore', 760, 100, 'Conserva anchors, poses world, correcciones aceptadas y control del tail.', 'pose'],
    ['covis_db', 'CovisibilityDatabase', 760, 260, 'Guarda covisibilidad nativa y relaciones geométricas confirmadas.', 'derived'],
    ['score_db', 'LandmarkScoreManager', 760, 390, 'Mantiene calidad, observaciones y estado publicable de MapPoints.', 'derived'],
    ['loop_detector', 'LoopDetector', 760, 540, 'Indexa BoW y produce candidatos después de filtros baratos.', 'secondary'],
    ['map_builder', 'GlobalMapBuilder', 1010, 100, 'Construye una vista coherente usando raw, poses, scores y fused tracks.', 'publication'],
    ['verifier', 'SubcloudLoopVerifier', 1010, 540, 'Ejecuta matching y RANSAC sobre snapshots privados.', 'secondary'],
    ['rviz2', 'RViz2', 1260, 100, 'Muestra PointCloud2 y MarkerArray pertenecientes a la misma revisión.', 'publication'],
    ['fused_db', 'FusedLandmarkManager', 1260, 300, 'Mantiene tracks fusionados y sus miembros raw.', 'derived'],
    ['decision', 'LoopDecisionManager', 1260, 540, 'Decide rechazo, fusión u optimización a partir de geometría confirmada.', 'secondary'],
    ['pose_graph', 'PoseGraphBuilder', 1490, 445, 'Construye grafos fiduciales o restricciones LOOP_RELATIVE sin escribir poses.', 'secondary'],
    ['optimizer', 'OptimizationManager', 1490, 595, 'Resuelve y valida candidatos privados antes del commit de poses.', 'secondary']
  ],
  edges: [
    ['wrapper_server_delta', 'wrappers', 'server', 'delta', 'ingest', 'OrbMap incremental: drone_id, map_epoch, secuencia, KFs y MapPoints modificados.', -22],
    ['wrapper_server_snapshot', 'wrappers', 'server', 'snapshot', 'ingest', 'OrbMap completo solicitado para reconciliar el estado raw de un submapa.', 22],
    ['server_raw_delta', 'server', 'raw_db', 'commit delta', 'ingest', 'Inserción incremental y RawInsertResult con IDs nuevos, revisiones y ChangeSet.', -22],
    ['server_raw_snapshot', 'server', 'raw_db', 'commit snapshot', 'ingest', 'Reemplazo/reconciliación de snapshot completo conservando la autoridad raw.', 22],
    ['server_fiducial_observation', 'server', 'fiducial', 'observación', 'pose', 'KF asociado, fiducial_id, pose absoluta simulada, timestamp y distancia.', 0],
    ['fiducial_pose_anchor', 'fiducial', 'pose_db', 'anchor inicial', 'pose', 'world_T_local, KF hard y metadatos del primer anclaje del submapa.', -16],
    ['fiducial_raw_journal', 'fiducial', 'raw_db', 'journal fiducial', 'ingest', 'Registro inmutable de la observación fiducial aceptada.', 16],
    ['raw_db_pose_new_kf', 'raw_db', 'pose_db', 'pose KF nuevo', 'pose', 'Pose raw y revisión usadas para registrar inmediatamente la pose world.', -18],
    ['raw_db_pose_snapshot', 'raw_db', 'pose_db', 'reconciliar poses', 'pose', 'Cambios raw de snapshot y KFs optimizados que deben conservar autoridad.', 18],
    ['raw_db_covisibility_db', 'raw_db', 'covis_db', 'covisibilidad ORB', 'derived', 'Conexiones nativas cambiadas y sus pesos ORB-SLAM3.', 0],
    ['raw_db_score_db', 'raw_db', 'score_db', 'scores', 'derived', 'Observaciones, found ratio, descriptor y estado bad de MapPoints.', 0],
    ['raw_db_secondary_queue', 'raw_db', 'queue', 'LoopTask', 'secondary', 'ID del KF nuevo, arrival_id, revisión y ChangeSet filtrado; nunca la base completa.', 0],
    ['fiducial_secondary_queue', 'fiducial', 'queue', 'tarea fiducial', 'secondary', 'FiducialOptimizationTask prioritaria con target absoluto y error medido.', 0],
    ['secondary_queue_loop_detector', 'queue', 'loop_detector', 'iniciar loop', 'secondary', 'Dequeue de una LoopTask normal; comienza su etapa BoW.', 0],
    ['loop_detector_loop_verifier', 'loop_detector', 'verifier', 'candidatos', 'secondary', 'KFs candidatos, ranking, BoW score y filtros superados.', 0],
    ['loop_verifier_loop_decision', 'verifier', 'decision', 'geometría', 'secondary', 'Transformación relativa, inliers, residuales, cobertura, confianza y error.', 0],
    ['loop_decision_covis_db', 'decision', 'covis_db', 'loop confirmado', 'derived', 'Arista geométrica confirmada y medida relativa inmutable.', 0],
    ['loop_decision_fused_db', 'decision', 'fused_db', 'fusión', 'derived', 'Pares de MapPoints inlier y actualización atómica de fused tracks.', 0],
    ['loop_decision_pose_graph', 'decision', 'pose_graph', 'optimizar loop', 'secondary', 'Restricción LOOP_RELATIVE y soportes independientes requeridos.', 0],
    ['secondary_queue_pose_graph', 'queue', 'pose_graph', 'optimizar fiducial', 'secondary', 'Tarea fiducial prioritaria capturada por el worker único.', 0],
    ['pose_graph_optimizer', 'pose_graph', 'optimizer', 'grafo privado', 'secondary', 'Vértices, aristas, priors hard, propagación y revisiones capturadas.', 0],
    ['optimizer_pose_db', 'optimizer', 'pose_db', 'commit poses', 'pose', 'Lote validado de poses optimizadas/propagadas y active tail anchor.', 0],
    ['server_map_builder', 'server', 'map_builder', 'solicitar vista', 'publication', 'Revisión solicitada y motivo; la petición no espera a RViz2.', -18],
    ['raw_db_map_builder', 'raw_db', 'map_builder', 'snapshot raw', 'publication', 'KFs, MapPoints y asociaciones de una captura coherente.', 0],
    ['pose_db_map_builder', 'pose_db', 'map_builder', 'snapshot poses', 'publication', 'Poses world y correcciones aceptadas de la misma captura.', -14],
    ['score_db_map_builder', 'score_db', 'map_builder', 'snapshot scores', 'publication', 'Scores y flags usados para filtrar y ponderar puntos.', 14],
    ['fused_db_map_builder', 'fused_db', 'map_builder', 'snapshot fused', 'publication', 'Tracks fusionados y miembros raw que deben omitirse.', 0],
    ['map_builder_server_view', 'map_builder', 'server', 'vista lista', 'publication', 'Nube global y marcadores de KFs construidos fuera del mutex live.', 18],
    ['server_rviz_cloud', 'server', 'rviz2', 'PointCloud2', 'publication', 'Nube sparse global con score, drone_id y map_epoch.', -22],
    ['server_rviz_keyframes', 'server', 'rviz2', 'MarkerArray KFs', 'publication', 'Poses de KeyFrames y borrados pertenecientes a la misma revisión.', 22]
  ]
};
