<?xml version="1.0"?>
<package format="3">
  <name>task_manager</name>
  <version>0.1.0</version>
  <description>Cliente ROS 2 de registro y lifecycle de mision a bordo.</description>
  <maintainer email="ivancalvosantos2003@uma.es">Ivan Calvo Santos</maintainer>
  <license>GPL-3.0-only</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>mission_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>task_manager_lib</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
