uint64 id

builtin_interfaces/Time stamp

geometry_msgs/Pose pose

uint32 camera_id
string frame_id

orbslam3_msgs/OrbKeyPoint[] keypoints

uint64[] mappoint_ids

uint64[] connected_keyframe_ids
uint32[] connected_keyframe_weights

bool is_bad

uint32[] bow_word_ids
float32[] bow_word_values

uint32[] feat_node_ids
uint32[] feat_node_start_indices
uint32[] feat_node_sizes
uint32[] feat_indices

uint64 parent_keyframe_id
uint64[] child_keyframe_ids
uint64[] loop_edge_keyframe_ids